vim.keymap.set('', '<leader>Y', '"+y$')
vim.keymap.set('', '<leader>p', '"+p')
vim.keymap.set('', '<leader>y', '"+y')
vim.keymap.set('', 'Y', 'y$')
vim.keymap.set('n', '<C-j>', ':m +1<cr>==')
vim.keymap.set('n', '<C-k>', ':m -2<cr>==')
vim.keymap.set('n', '<leader>cn', ':cnext<cr>')
vim.keymap.set('n', '<leader>co', ':copen<cr>')
vim.keymap.set('n', '<leader>cp', ':cprev<cr>')
vim.keymap.set('n', '<leader>rl', ':set relativenumber!<cr>')
vim.keymap.set('n', '<leader>sl', ':set list!<cr>')
vim.keymap.set('n', '<leader>sw', [[:%s/\<<C-r><C-w>\>/<C-r><C-w>/gI<Left><Left><Left>]])
vim.keymap.set('n', '<leader>vc', ':e ~/.config/nvim/init.vim<cr>')
vim.keymap.set('n', '<leader>yf', ':let @+ = expand("%:.")<cr>')
vim.keymap.set('n', 'N', 'Nzzzv')
vim.keymap.set('n', 'n', 'nzzzv')
vim.keymap.set('t', '<leader><Esc>', '<C-\\><C-n>')
vim.keymap.set('v', '<C-j>', ":m '>+1<cr>gv=gv")
vim.keymap.set('v', '<C-k>', ":m '<-2<cr>gv=gv")
