vim.keymap.set('', '<leader>Y', '"+y$')
vim.keymap.set('', '<leader>p', '"+p')
vim.keymap.set('', '<leader>y', '"+y')
vim.keymap.set('', 'Y', 'y$')
vim.keymap.set('n', '<C-j>', ':m +1<cr>==')
vim.keymap.set('n', '<C-k>', ':m -2<cr>==')
vim.keymap.set('n', '<leader>cn', ':cnext<cr>')
vim.keymap.set('n', '<leader>co', ':copen<cr>')
vim.keymap.set('n', '<leader>cp', ':cprev<cr>')
vim.keymap.set('n', '<leader>rl', ':set relativenumber!<cr>')
vim.keymap.set('n', '<leader>sl', ':set list!<cr>')
vim.keymap.set('n', '<leader>sw', [[:%s/\<<C-r><C-w>\>/<C-r><C-w>/gI<Left><Left><Left>]])
vim.keymap.set('n', '<leader>vc', ':e ~/.config/nvim/init.lua<cr>')
vim.keymap.set('n', '<leader>yf', ':let @+ = expand("%:.")<cr>')
vim.keymap.set('n', 'N', 'Nzzzv')
vim.keymap.set('n', 'n', 'nzzzv')
vim.keymap.set('t', '<leader><Esc>', '<C-\\><C-n>')
vim.keymap.set('v', '<C-j>', ":m '>+1<cr>gv=gv")
vim.keymap.set('v', '<C-k>', ":m '<-2<cr>gv=gv")
vim.keymap.set('n', '<leader>gs', function()
  require('neogit').open({ kind = 'split_above', cwd = vim.fn.expand('%:p:h') })
end)
vim.keymap.set('n', '<leader>gb', function() require('gitsigns').blame() end)
vim.keymap.set('n', '<leader>mm', function() require('harpoon.mark').add_file() end)
vim.keymap.set('n', '<leader>mo', function() require('harpoon.ui').toggle_quick_menu() end)
vim.keymap.set('n', '<leader>ma', function() require('harpoon.ui').nav_file(1) end)
vim.keymap.set('n', '<leader>mb', function() require('harpoon.ui').nav_file(2) end)
vim.keymap.set('n', '<leader>mc', function() require('harpoon.ui').nav_file(3) end)
vim.keymap.set('n', '<leader>md', function() require('harpoon.ui').nav_file(4) end)
vim.keymap.set('n', '<leader>e', '<cmd>Oil<cr>')
vim.keymap.set('n', '<leader>f', function()
  require('telescope.builtin').find_files({ hidden = true })
end)
vim.keymap.set('n', '<leader>rg', function() require('telescope.builtin').live_grep() end)
vim.keymap.set('n', '<leader>rr', function() require('telescope.builtin').resume() end)
vim.keymap.set('n', '<leader>hg', function() require('telescope.builtin').help_tags() end)
vim.keymap.set('n', '<leader>rw', function() require('telescope.builtin').grep_string() end)
vim.keymap.set('n', '<leader>rq', function() require('telescope.builtin').quickfix() end)
vim.keymap.set('n', '<leader>t', function() require('telescope.builtin').builtin() end)
vim.keymap.set('n', '<leader>i', function()
  require('telescope.builtin').symbols({ sources = {'emoji', 'kaomoji', 'gitmoji'} })
end)
vim.keymap.set('n', '<leader>li', vim.lsp.buf.format)
vim.keymap.set('n', '<leader>zn', function()
  require('zk.commands').get('ZkNew')({ title = vim.fn.input('Title: ') })
end)
vim.keymap.set('n', '<leader>zf', function()
  require('zk.commands').get('ZkNotes')({ sort = { 'modified' }, tags = { '-person' } })
end)
vim.keymap.set('n', '<leader>zt', function() require('zk.commands').get('ZkTags')() end)
vim.keymap.set('n', '<leader>zi', function() require('zk.commands').get('ZkInsertLink')() end)
vim.keymap.set('n', '<leader>zb', function() require('zk.commands').get('ZkBacklinks')() end)
vim.keymap.set('n', '<leader>zw', ":'<,'>ZkMatch<cr>")
vim.keymap.set('n', '<leader>ga', '<cmd>A<cr>')
vim.keymap.set('n', '<leader>gr', '<cmd>OpenInGHRepo<cr>')
vim.keymap.set('n', '<leader>gf', '<cmd>OpenInGHFile<cr>')
vim.keymap.set('v', '<leader>gf', '<cmd>OpenInGHFileLines<cr>')
vim.keymap.set('n', '<leader>zm', function() require("zen-mode").toggle() end)
